defaults:
  - run: comparative-2-MobileNetV2-0.5-3.5M-CIFAR-10

# List of every run id covered in this project
all_runs:
  - comparative-2-MobileNetV2-0.5-3.5M-CIFAR-10
  - comparative-2-MobileNetV2-0.5-3.5M-alpaca-cleaned
  - comparative-2-DistilBERT-base-66M-CIFAR-10
  - comparative-2-DistilBERT-base-66M-alpaca-cleaned

# The run id to execute can be overridden via CLI (e.g. run=<run_id> or run=all)
run: comparative-2-MobileNetV2-0.5-3.5M-CIFAR-10

# Default location for results (can be overridden by CLI)
results_dir: ./results

# WandB defaults
wandb:
  entity: gengaru617
  project: 251014-test
  tags: ["hydra", "benchmark"]

# Any other global defaults can be added here

version: 1.0

